### ISSUE TITLE
spec_agnostic error

### ISSUE THREAD

**Issue by alecpwills** [semodi/neuralxc#6]
Using the template files provided in `examples/example_scripts/train_model`, but on aspirin or ethanol from sGDML's datasets yields the following error. Changing `spec_agnostic` from `false` to `true` doesn't produce the error.

```
...
Epoch 2000 ||  Training loss : 0.034451  Validation loss : 0.000000  Learning rate: 1.0000000000000002e-07
21
(9, 15, 160)
(4, 15, 160)
(8, 15, 36)
====== Iteration 1 ======
Using symmetrizer  trace
Traceback (most recent call last):
  File "/home/awills/Documents/Research/neuralxc/neuralxc/ml/pipeline.py", line 245, in serialize_pipeline
    projector = DensityProjector(basis_instructions=basis_instructions, unitcell=unitcell_c, grid=grid_c)
  File "/home/awills/Documents/Research/neuralxc/neuralxc/projector/projector.py", line 42, in DensityProjector
    return registry[projector_type](**kwargs)
TypeError: __init__() missing 1 required positional argument: 'mol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awills/Documents/Research/neuralxc/neuralxc/ml/pipeline.py", line 251, in serialize_pipeline
    grid_weights=grid_c)
  File "/home/awills/Documents/Research/neuralxc/neuralxc/projector/projector.py", line 42, in DensityProjector
    return registry[projector_type](**kwargs)
TypeError: __init__() missing 1 required positional argument: 'mol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awills/anaconda3/envs/nxc/bin/neuralxc", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/awills/Documents/Research/neuralxc/bin/neuralxc", line 266, in <module>
    func(**args_dict)
  File "/home/awills/Documents/Research/neuralxc/neuralxc/drivers/model.py", line 249, in sc_driver
    'radial' in pre['preprocessor'].get('projector_type', 'ortho'))
  File "/home/awills/Documents/Research/neuralxc/neuralxc/drivers/model.py", line 131, in serialize
    xc.ml.pipeline.serialize_pipeline(model, jit_path, override=True)
  File "/home/awills/Documents/Research/neuralxc/neuralxc/ml/pipeline.py", line 260, in serialize_pipeline
    serialize_energy(model, C, outpath, override)
  File "/home/awills/Documents/Research/neuralxc/neuralxc/ml/pipeline.py", line 172, in serialize_energy
    e_models[spec] = torch.jit.trace(epred, c, check_trace=False)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/torch/jit/_trace.py", line 940, in trace_module
    _force_outplace,
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/awills/Documents/Research/neuralxc/neuralxc/ml/pipeline.py", line 142, in forward
    return self.model(C)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/awills/Documents/Research/neuralxc/neuralxc/ml/transformer.py", line 129, in forward
    return self.transform(X, wrap_torch=False)
  File "/home/awills/Documents/Research/neuralxc/neuralxc/ml/transformer.py", line 79, in transform
    results_dict[spec] = self._spec_dict[spec].transform(x[spec])
KeyError: 'X'
```

**Comment by semodi** [comment]
resolved by 7e0509d
