### ISSUE TITLE
basis nworkers error

### ISSUE THREAD

**Issue by alecpwills** [semodi/neuralxc#7]
Changing `nworkers=1` to anything above 1 in the basis.json file causes the following error for any molecule I try it on:

```
====== Iteration 0 ======
Calculating 15 systems on
LocalCluster(d5f9cd8d, 'tcp://127.0.0.1:42955', workers=2, threads=2, memory=16.70 GB)
Traceback (most recent call last):
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/distributed/worker.py", line 3398, in dumps_function
    result = cache_dumps[func]
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/distributed/utils.py", line 1523, in __getitem__
    value = super().__getitem__(key)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/collections/__init__.py", line 991, in __getitem__
    raise KeyError(key)
KeyError: <function in_private_dir.<locals>.wrapper_private_dir at 0x7f66774bd950>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 49, in dumps
    result = pickle.dumps(x, **dump_kwargs)
AttributeError: Can't pickle local object 'in_private_dir.<locals>.wrapper_private_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awills/anaconda3/envs/nxc/bin/neuralxc", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/awills/Documents/Research/neuralxc/bin/neuralxc", line 266, in <module>
    func(**args_dict)
  File "/home/awills/Documents/Research/neuralxc/neuralxc/drivers/model.py", line 209, in sc_driver
    kwargs=engine_kwargs)
  File "/home/awills/Documents/Research/neuralxc/neuralxc/preprocessor/driver.py", line 141, in driver
    results = calculate_distributed(atoms, app, dir, kwargs, nworkers)
  File "/home/awills/Documents/Research/neuralxc/neuralxc/preprocessor/driver.py", line 106, in calculate_distributed
    [app] * len(atoms), [kwargs] * len(atoms))
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/distributed/client.py", line 1774, in map
    actors=actor,
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/distributed/client.py", line 2542, in _graph_to_futures
    dsk = dsk.__dask_distributed_pack__(self, keyset)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/dask/highlevelgraph.py", line 939, in __dask_distributed_pack__
    client_keys,
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/dask/highlevelgraph.py", line 392, in __dask_distributed_pack__
    dsk = toolz.valmap(dumps_task, dsk)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/toolz/dicttoolz.py", line 83, in valmap
    rv.update(zip(d.keys(), map(func, d.values())))
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/distributed/worker.py", line 3436, in dumps_task
    return {"function": dumps_function(task[0]), "args": warn_dumps(task[1:])}
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/distributed/worker.py", line 3400, in dumps_function
    result = pickle.dumps(func, protocol=4)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 60, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/cloudpickle/cloudpickle_fast.py", line 102, in dumps
    cp.dump(obj)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/cloudpickle/cloudpickle_fast.py", line 745, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/cloudpickle/cloudpickle_fast.py", line 682, in _save_reduce_pickle5
    dictitems=dictitems, obj=obj
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/awills/anaconda3/envs/nxc/lib/python3.6/site-packages/dill/_dill.py", line 1169, in save_cell
    f = obj.cell_contents
ValueError: Cell is empty
```

**Comment by semodi** [comment]
The error occurs when trying to pickle a function that was modified by a decorator. This only occurred in for certain versions of pickle (and "dill"). I removed the decorator which should fix the issue.
